[build-system]
requires = ["pygo-tools"]

[tool.cibuildwheel]
before-all = "uname -a"

[tool.cibuildwheel.linux]
before-build = "yum install -y golang make"

# cibuildwheel --platform linux --arch x86_64