[tool.cibuildwheel]
environment = {GO_VERSION="1.21.8", ASDF_VERSION="0.14.0"}
skip = ["*-musllinux*"]

[tool.cibuildwheel.linux]
before-all = [
    "yum install -y make zip"
]
before-build = [
    "uname -a",
    "pip install pygo-tools",
    "{package}/scripts/install-asdf-go.sh"
]
repair-wheel-command = "auditwheel repair --lib-sdir lib -w {dest_dir} {wheel}"

[[tool.cibuildwheel.overrides]]
select="*-????linux_*"
inherit.environment="append"
environment.ASDF_DIR = "/opt/asdf"

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = [
    "apk add make zip",
]

[tool.cibuildwheel.macos]
before-build = [
    "uname -a",
    "pip install pygo-tools"
]
repair-wheel-command = [
    # NOTE: placeholder for package does not resolve
    "cd ${package:-.}/ && python scripts/patch-macos-wheel.py --wheel {wheel}",
    "cp {wheel} {dest_dir}"
#    "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
]
