name: build pygo-jwt

#on:
#  workflow_dispatch:

on:
  push:
    branches:
      - feature/cicd

jobs:
  build_wheels:
    name: build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [macos-13]
#        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        if: ${{ contains(fromJSON('["macos", "windows"]'), runner.os) }}
        with:
          go-version: 1.21.8

      - name: build wheels
        uses: pypa/cibuildwheel@v2.17.0
        with:
          package-dir: pygo-jwt
          output-dir: wheelhouse
          config-file: "{package}/wheel.toml"

#      - uses: actions/upload-artifact@v4
#        with:
#          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
#          path: ./wheelhouse/*.whl
